#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2012 OpenWrt.org
# patch by yinjiajin@xiaomi.com, use conf-dir

START=97
STOP=97

PIDFILE="/tmp/dnsfixd.pid"

set_smartvpn_switch_on="uci set smartvpn.vpn.disabled=0"
set_smartvpn_switch_off="uci set smartvpn.vpn.disabled=1"
set_switch_commit="uci commit smartvpn"

export EXTRA_COMMANDS=" on off"
export EXTRA_HELP="        on      Switch to the start state and start
        off     Switch to the stop state and stop"

on() {
        uci set dnsfixd.global.disabled=0;
        uci commit dnsfixd

        [ -f $PIDFILE ] && kill $(cat $PIDFILE)
        rm $PIDFILE

        /usr/sbin/dnsfixd &
}

off() {
        uci set dnsfixd.global.disabled=1;
        uci commit dnsfixd
        [ -f $PIDFILE ] && kill $(cat $PIDFILE)
        killall -9 dnsfixd 2>/dev/null 1>/dev/null
}

start() {
        disabled=$(uci get dnsfixd.global.disabled)
        [ $disabled == "1" ] && return

        [ -f $PIDFILE ] && kill $(cat $PIDFILE)
        rm $PIDFILE

        /usr/sbin/dnsfixd &
}

stop() {
        [ -f $PIDFILE ] && kill $(cat $PIDFILE)
        killall -9 dnsfixd 2>/dev/null 1>/dev/null
}

