#!/bin/sh /etc/rc.common

START=99

EXTRA_COMMANDS=" on off "
EXTRA_HELP=""

CCGAME_service="/usr/sbin/ccgame_service.lua"
IPV6_service="/usr/sbin/ipv6_service.lua"
CMD_CCGAME_service="lua $CCGAME_service"
CMD_IPV6_service="lua $IPV6_service"

start() {
    [ -f "$CCGAME_service" ] && start_ccgame
    [ -f "$IPV6_service" ] && start_ipv6
    return 0
}

stop() {
    [ -f "$CCGAME_service" ] && stop_ccgame
    [ -f "$IPV6_service" ] && stop_ipv6
    return 0
}

start_ccgame(){
    export PROCLINE=$CMD_CCGAME_service
    export PROCFLAG=$PROCLINE
    /usr/sbin/supervisord start

    return 0
}

stop_ccgame(){
    export PROCLINE=$CMD_CCGAME_service
    export PROCFLAG=$PROCLINE
    /usr/sbin/supervisord stop

    return 0
}

start_ipv6(){
    #/etc/init.d/ipv6 on ipv6
    export PROCLINE=$CMD_IPV6_service
    export PROCFLAG=$PROCLINE
    /usr/sbin/supervisord start

    return 0
}

stop_ipv6(){
    #/etc/init.d/ipv6 off ipv6
    export PROCLINE=$CMD_IPV6_service
    export PROCFLAG=$PROCLINE
    /usr/sbin/supervisord stop

    return 0
}
