#!/bin/sh

del_elink_en_from_bdata() {
	elink=`bdata get elink_en`
	[ "$elink" = "" ] && return

	echo 1 > /proc/xiaoqiang/unlock_bdata
	bdata unset elink_en
	bdata commit
	echo 0 > /proc/xiaoqiang/unlock_bdata
}

boot_hook_add preinit_main del_elink_en_from_bdata

