#!/bin/sh

get_interface_tmp() {
    local _iface="$1"
    local _tempfile="/tmp/state/${_iface}_temp"
    local _temp
    local _old_temp
    local _delta

    _temp=$(iwpriv $_iface stat | grep CurrentTemperature | cut -d'=' -f2 | tr -d ' ')
    if [ -f "$_tempfile" ]; then
	_old_temp=$(cat "$_tempfile")
	_delta=$(($_temp-$_old_temp))
	[ $_delta -gt 45 ] && {
	    logger -t mt7615etemp -p9 "**********WARNING!! TEMP delta of 7615e > 45C on $_iface *******"
	    echo $_temp > "$_tempfile"
	}
	_delta=$(($_old_temp-$_temp))
	[ $_delta -gt 45 ] && {
	    logger -t mt7615etemp -p9 "**********WARNING!! TEMP delta of 7615e > 45C on $_iface *******"
	    echo $_temp > "$_tempfile"
	}
    else
	echo $_temp > "$_tempfile"
    fi
}

get_interface_tmp wl0
get_interface_tmp wl1
