#!/bin/sh /etc/rc.common

START=99

EXTRA_COMMANDS="on off init_ipt status"

start() {
    #check NETMODE 1stly
    local mode
    mode=`uci -q get xiaoqiang.common.NETMODE`
    if [ "$mode" == "wifiapmode" -o "$mode" == "lanapmode" ]; then
        echo "In AP mode, disable QoS. exit!"
        return 0
    fi

    local enabled
    enabled=`uci -q get miqos.settings.enabled`
    [ "$enabled" = "1" ] && {
        /usr/sbin/miqosd on
    }

    return 0
}

stop() {

    /usr/sbin/miqosd off
    return 0
}

restart(){
    stop
    start
    return 0
}

on(){
    uci set miqos.settings.enabled=1
    uci commit miqos

    start
}

off(){
    uci set miqos.settings.enabled=0
    uci commit miqos

    stop
}

init_ipt(){
   /usr/sbin/miqosd_init.sh
   return $?
}

# status: 0, actived, 1, inactived
status(){
    local enabled
    enabled=`uci -q get miqos.settings.enabled`
    [ "$enabled" = "1" ] && {
        return 0
    }
    return 1
}
