#!/bin/sh /etc/rc.common

START=99

CFG_PATH="/proc/sys/net/ipv4/tcp_proxy_action"
SWITCH_PATH="/proc/sys/net/ipv4/tcp_proxy_switch"
LIP=`uci get network.lan.ipaddr 2>/dev/null`
PROXY_PORT=8383

set_switch_on="uci set http_event_proxy.settings.enabled=1"
set_switch_off="uci set http_event_proxy.settings.enabled=0"
set_switch_commit="uci commit http_event_proxy"
APP_CTF_MGR="/usr/sbin/ctf_manger.sh"
service_name="http_event_proxy"
fastpath=""
ipset_name="rr_de"
src_port=80
local_port=8385

export EXTRA_COMMANDS=" on off "
export EXTRA_HELP="	on	Switch to the start state and start
	off	Switch to the stop state and stop"

EventService_EXECMD="/usr/sbin/eventservice"

create_ctf_mgr_entry()
{
    uci -q batch <<EOF > /dev/null
set ctf_mgr.$service_name=service
set ctf_mgr.$service_name.http_switch=off
commit ctf_mgr
EOF
}

start() {
    switch=`uci get http_event_proxy.settings.enabled -q`
    if [ $switch -ne "1" ]; then
        #if not enabled, just exit
        return 0
    fi

    fastpath=`uci get misc.http_proxy.fastpath -q`
    [ -z $fastpath ] && return 0

    if [ $fastpath == "ctf" ]; then
        if [ -f $APP_CTF_MGR ]; then
            is_exist=`uci get ctf_mgr.$service_name -q`
            if [ $? -eq "1" ]; then
                create_ctf_mgr_entry
            fi
            $APP_CTF_MGR $service_name http on
        else
            echo "http client detect: no ctf mgr found!"
            return 0
        fi
    elif [ $fastpath == "hwnat" ]; then
        echo "http client detect: can work with hw_nat."
    else
        echo "http client detect: unknown fastpath! Treat as std!"
    fi
    insmod nf_conn_ext_http >/dev/null 2>&1
    insmod nf_tcp_proxy >/dev/null 2>&1
    # ensure start switch
    echo "ADD 8 $LIP $PROXY_PORT" > $CFG_PATH
    echo "1" > $SWITCH_PATH
    insmod http_event >/dev/null 2>&1

    # for domain event
    ipset_redirect.sh create $ipset_name $src_port $local_port

    export PROCLINE="${EventService_EXECMD}"
    export PROCNUM='1'
    /usr/sbin/supervisord start

    return 0
}

stop() {
    killall eventservice >/dev/null 2>&1
    export PROCLINE="${EventService_EXECMD}"
    export PROCNUM='1'
    /usr/sbin/supervisord stop

    # for domain event
    ipset_redirect.sh destroy $ipset_name $src_port $local_port

    rmmod http_event >/dev/null 2>&1
    rmmod nf_tcp_proxy >/dev/null 2>&1

    fastpath=`uci get misc.http_proxy.fastpath -q`
    [ -z $fastpath ] && return 0

    if [ $fastpath == "ctf" ]; then
        if [ -f $APP_CTF_MGR ]; then
            $APP_CTF_MGR $service_name http off
        fi
    elif [ $fastpath == "hwnat" ]; then
        echo "http client detect stopped."
    else
        echo "http client detect: unknown fastpath! Treat as std!"
    fi
    return 0
}

off() {
    $set_switch_off >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    stop
    return $?
}

on() {
    $set_switch_on >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1

    start
    return $?
}

