#!/bin/sh /etc/rc.common

START=99

set_switch_on="uci set ustack.settings.enabled=1"
set_switch_off="uci set ustack.settings.enabled=0"
set_switch_commit="uci commit ustack"

APP_CTF_MGR="/usr/sbin/ctf_manger.sh"
export EXTRA_COMMANDS=" on off log_stat"
export EXTRA_HELP="	on	Switch to the start state and start
	off	Switch to the stop state and stop"

USTACK_EXECMD="/usr/sbin/ustackd br-lan"
USTACK_EXTRA_FLAG="/usr/sbin/ustackd br-lan"


start() {
    config_load "ustack"
    local switch
    local ap_mode
    switch=`uci get ustack.settings.enabled -q`
    ap_mode=`uci get xiaoqiang.common.NETMODE -q`

    if [ $switch -ne "1" ]; then
        return 0
    fi

    if [ "$ap_mode" != "" ]; then
        return 0
    fi

    local cc=$(bdata get CountryCode)
    cc=${cc:-"CN"}
    if [ $cc != "CN" ]; then
        echo "http_stat: Bad Country!"
        return 0
    fi

    export PROCLINE="${USTACK_EXECMD}"
    export PROCFLAG="${USTACK_EXTRA_FLAG}"
    export PROCNUM='1'
    /usr/sbin/supervisord start

    return 0
}

stop() {
    kill -9 `cat /tmp/ustack.pid`
    export PROCLINE="${USTACK_EXECMD}"
    export PROCFLAG="${USTACK_EXTRA_FLAG}"
    /usr/sbin/supervisord stop

    return 0
}

off(){
    stop
    $set_switch_off >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    $restart_dnsmasq
    return $?
}

on(){
    $set_switch_on >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    $restart_dnsmasq
    start
    return $?
}

